Use WAREHOUSE COMPUTE_WH;
USE DATABASE SNOWFLAKE_LEARNING_DB;
CREATE SCHEMA IF NOT EXISTS GOLD;

CREATE OR REPLACE TABLE GOLD.SALES_BY_STATE AS
SELECT
    d.state,
    SUM(f.sales_price) AS total_sales
FROM SILVER.FACT_SALES f
JOIN SILVER.CUSTOMER_DIM d  
    ON f.customer_sk=d.customer_sk
GROUP BY d.state;


CREATE OR REPLACE TABLE GOLD.SALES_BY_YEAR AS
SELECT
    YEAR(transaction_date) AS sales_year,
    SUM(sales_price) AS total_sales
FROM SILVER.FACT_SALES
GROUP BY sales_year;